package main.form;

import java.util.Objects;
import javax.swing.DefaultListModel;
import worker.Worker;
import worker.WorkerException;
import worker.WorkerTableModel;

public class form1 extends javax.swing.JFrame {

    //<editor-fold defaultstate="collapsed" desc="Constructor"> 
    public form1() {
        initComponents();
        setModels();
        //setWorkerTableModel();
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="(Mostly) irrelevant code"> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIdentification = new javax.swing.JPanel();
        lblSurnameTwo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurnameOne = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurnameOne = new javax.swing.JTextField();
        txtSurnameTwo = new javax.swing.JTextField();
        pnlProvince = new javax.swing.JPanel();
        cmbProvince = new javax.swing.JComboBox<>();
        txtProvinceAdd = new javax.swing.JTextField();
        btnProvinceRemove = new javax.swing.JButton();
        btnProvinceAdd = new javax.swing.JButton();
        pnlAvailable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblWorker = new javax.swing.JTable();
        pnlDetails = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtWorkerDetails = new javax.swing.JTextArea();
        pnlProfession = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProfession = new javax.swing.JList<>();
        btnProfessionRemove = new javax.swing.JButton();
        txtProfessionAdd = new javax.swing.JTextField();
        btnProfessionAdd = new javax.swing.JButton();
        btnWorkerRemove = new javax.swing.JButton();
        btnWorkerAdd = new javax.swing.JButton();
        btnAppClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        pnlIdentification.setBorder(javax.swing.BorderFactory.createTitledBorder("Identificación do traballador"));

        lblSurnameTwo.setText("Apelido 2");

        lblID.setText("DNI");

        lblName.setText("Nome");

        lblSurnameOne.setText("Apelido 1");

        txtID.setText("12345678@");

        txtName.setText("Pepe");

        txtSurnameOne.setText("Apelido 2 triggers exception");

        javax.swing.GroupLayout pnlIdentificationLayout = new javax.swing.GroupLayout(pnlIdentification);
        pnlIdentification.setLayout(pnlIdentificationLayout);
        pnlIdentificationLayout.setHorizontalGroup(
            pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentificationLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSurnameTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurnameOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addGroup(pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID)
                    .addComponent(txtName)
                    .addComponent(txtSurnameOne, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(txtSurnameTwo))
                .addContainerGap())
        );
        pnlIdentificationLayout.setVerticalGroup(
            pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentificationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurnameOne)
                    .addComponent(txtSurnameOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurnameTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurnameTwo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlIdentification);
        pnlIdentification.setBounds(10, 10, 520, 220);

        pnlProvince.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincia do traballador"));

        txtProvinceAdd.setText("A Coruña");

        btnProvinceRemove.setText("Eliminar provincia");
        btnProvinceRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvinceRemoveActionPerformed(evt);
            }
        });

        btnProvinceAdd.setText("Engadir provincia");
        btnProvinceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvinceAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProvinceLayout = new javax.swing.GroupLayout(pnlProvince);
        pnlProvince.setLayout(pnlProvinceLayout);
        pnlProvinceLayout.setHorizontalGroup(
            pnlProvinceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProvinceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProvinceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProvinceAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(cmbProvince, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlProvinceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProvinceRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProvinceAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlProvinceLayout.setVerticalGroup(
            pnlProvinceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProvinceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProvinceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProvinceRemove))
                .addGap(18, 18, 18)
                .addGroup(pnlProvinceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvinceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProvinceAdd))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(pnlProvince);
        pnlProvince.setBounds(10, 240, 520, 120);

        pnlAvailable.setBorder(javax.swing.BorderFactory.createTitledBorder("Traballadores dispoñibles"));

        tblWorker.setAutoCreateRowSorter(true);
        tblWorker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre y apellidos", "Provincia", "Profesión"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorker.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblWorker.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblWorker.getTableHeader().setReorderingAllowed(false);
        tblWorker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWorkerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblWorker);
        tblWorker.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblWorker.getColumnModel().getColumnCount() > 0) {
            tblWorker.getColumnModel().getColumn(0).setResizable(false);
            tblWorker.getColumnModel().getColumn(1).setResizable(false);
            tblWorker.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pnlAvailableLayout = new javax.swing.GroupLayout(pnlAvailable);
        pnlAvailable.setLayout(pnlAvailableLayout);
        pnlAvailableLayout.setHorizontalGroup(
            pnlAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvailableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAvailableLayout.setVerticalGroup(
            pnlAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvailableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlAvailable);
        pnlAvailable.setBounds(540, 10, 520, 310);

        pnlDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles do traballador"));

        txtWorkerDetails.setColumns(20);
        txtWorkerDetails.setRows(5);
        jScrollPane2.setViewportView(txtWorkerDetails);

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlDetails);
        pnlDetails.setBounds(540, 370, 520, 250);

        pnlProfession.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesión do traballador"));

        jScrollPane1.setViewportView(lstProfession);

        btnProfessionRemove.setText("Eliminar profesión");
        btnProfessionRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessionRemoveActionPerformed(evt);
            }
        });

        txtProfessionAdd.setText("Carpintero");

        btnProfessionAdd.setText("Engadir profesión");
        btnProfessionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessionAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProfessionLayout = new javax.swing.GroupLayout(pnlProfession);
        pnlProfession.setLayout(pnlProfessionLayout);
        pnlProfessionLayout.setHorizontalGroup(
            pnlProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProfessionAdd)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfessionRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfessionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlProfessionLayout.setVerticalGroup(
            pnlProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfessionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfessionRemove)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProfessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfessionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfessionAdd))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pnlProfession);
        pnlProfession.setBounds(10, 370, 520, 250);

        btnWorkerRemove.setText("Eliminar traballador");
        btnWorkerRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkerRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnWorkerRemove);
        btnWorkerRemove.setBounds(540, 330, 520, 25);

        btnWorkerAdd.setText("Engadir traballador");
        btnWorkerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkerAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnWorkerAdd);
        btnWorkerAdd.setBounds(10, 630, 520, 25);

        btnAppClose.setText("Pechar aplicación");
        btnAppClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppClose);
        btnAppClose.setBounds(540, 630, 520, 25);

        setSize(new java.awt.Dimension(1089, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Gestión sobre provincias"> 
    private void btnProvinceRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvinceRemoveActionPerformed
        Object selectedItem = cmbProvince.getSelectedItem();
        if (Objects.isNull(selectedItem)) {
            formController.errorMessage(this, "Ninguna provincia seleccionada.");
            return;
        }
        cmbProvince.removeItem(selectedItem);
        if (cmbProvince.getItemCount() < 1) {
            cmbProvince.setSelectedItem(null);
        }
    }//GEN-LAST:event_btnProvinceRemoveActionPerformed

    private void btnProvinceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvinceAddActionPerformed
        String province = txtProvinceAdd.getText();
        if (province.isBlank()) {
            formController.errorMessage(this, "No se puede registrar una provincia en blanco.");
            return;
        }
        cmbProvince.addItem(province);

    }//GEN-LAST:event_btnProvinceAddActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Gestión sobre profesiones"> 
    private void btnProfessionRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessionRemoveActionPerformed
        int[] selectedProfessions = lstProfession.getSelectedIndices();
        if (selectedProfessions.length < 1) {
            formController.errorMessage(this, "Ninguna profesión seleccionada para su borrado.");
            return;
        }
        for (int i = 0; i < selectedProfessions.length; i++) {
            listModel.removeElement(selectedProfessions[i]);
        }


    }//GEN-LAST:event_btnProfessionRemoveActionPerformed

    private void btnProfessionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessionAddActionPerformed
        String profession = txtProfessionAdd.getText();
        if (profession.isBlank()) {
            formController.errorMessage(this, "No hay una profesión a añadir. El campo de texto está en blanco.");
            return;
        }
        listModel.addElement(profession);

    }//GEN-LAST:event_btnProfessionAddActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Gestión sobre trabajadores">
    private void btnWorkerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkerAddActionPerformed
        try {
            Worker worker = generateWorker();
            if (tableModel.existsWorker(worker)) {
                formController.errorMessage(this, "El trabajador con DNI " + worker.getId() + " ya está registrado.");
                return;
            }
            tableModel.addWorker(worker);
        } catch (WorkerException ex) {
            formController.errorMessage(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnWorkerAddActionPerformed
    private void btnWorkerRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkerRemoveActionPerformed
        int selectedRow = tblWorker.getSelectedRow();
        if (selectedRow != -1) {
            Worker worker = tableModel.getWorkerAt(selectedRow);
            tableModel.removeRow(selectedRow);
            updateDetails();
            formController.infoMessage(this, "Borrado:\n" + worker.toString());
        }
    }//GEN-LAST:event_btnWorkerRemoveActionPerformed


    private void tblWorkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWorkerMouseClicked
        if (evt.getClickCount() == 1) {
            int selectedRow = tblWorker.getSelectedRow();
            if (selectedRow != -1) {
                Worker worker = tableModel.getWorkerAt(selectedRow);
                txtWorkerDetails.setText(worker.toStringFormatted());
            }
        }
        if (evt.getClickCount() == 2) {
            int selectedRow = tblWorker.getSelectedRow();
            if (selectedRow != -1) {
                Worker worker = tableModel.getWorkerAt(selectedRow);
                int countBySimilarProvince = tableModel.countBySimilarProvince(worker);
                formController.infoMessage(this, "Misma provincia: " + countBySimilarProvince + " traballadores.");
            }
        }
    }//GEN-LAST:event_tblWorkerMouseClicked
    //</editor-fold>    
    private void btnAppCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnAppCloseActionPerformed

    //<editor-fold defaultstate="collapsed" desc="Main">
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new form1().setVisible(true);
        });
    }
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppClose;
    private javax.swing.JButton btnProfessionAdd;
    private javax.swing.JButton btnProfessionRemove;
    private javax.swing.JButton btnProvinceAdd;
    private javax.swing.JButton btnProvinceRemove;
    private javax.swing.JButton btnWorkerAdd;
    private javax.swing.JButton btnWorkerRemove;
    private javax.swing.JComboBox<String> cmbProvince;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSurnameOne;
    private javax.swing.JLabel lblSurnameTwo;
    private javax.swing.JList<String> lstProfession;
    private javax.swing.JPanel pnlAvailable;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlIdentification;
    private javax.swing.JPanel pnlProfession;
    private javax.swing.JPanel pnlProvince;
    private javax.swing.JTable tblWorker;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProfessionAdd;
    private javax.swing.JTextField txtProvinceAdd;
    private javax.swing.JTextField txtSurnameOne;
    private javax.swing.JTextField txtSurnameTwo;
    private javax.swing.JTextArea txtWorkerDetails;
    // End of variables declaration//GEN-END:variables
    //<editor-fold defaultstate="collapsed" desc="Variables y gestión frame">
    WorkerTableModel tableModel = new WorkerTableModel();
    DefaultListModel<String> listModel = new DefaultListModel<>();

    private void setWorkerTableModel() {
        tblWorker.setModel(tableModel);
        tblWorker.setDefaultEditor(Object.class, null);
    }

    private void setModels() {
        setWorkerTableModel();
        lstProfession.setModel(listModel);
    }

    public void updateDetails() {
        if (!txtWorkerDetails.getText().isBlank()) {
            txtWorkerDetails.setText("");
        }
    }
    //</editor-fold>

    private Worker generateWorker() throws WorkerException {
        String id = txtID.getText();
        String name = txtName.getText();
        String surnameOne = txtSurnameOne.getText();
        String surnameTwo = txtSurnameTwo.getText();
        String province, profession;
        if (id.isBlank()) {
            throw new WorkerException("El campo DNI " + "no puede estar en blanco.");
        }
        if (name.isBlank()) {
            throw new WorkerException("El campo nombre" + "no puede estar en blanco.");
        }
        if (surnameOne.isBlank()) {
            throw new WorkerException("El campo apellido 1 " + "no puede estar en blanco.");
        }
        if (surnameTwo.isBlank()) {
            throw new WorkerException("El campo apellido 2 " + "no puede estar en blanco.");
        }
        province = (String) cmbProvince.getSelectedItem();
        if (Objects.isNull(province)) {
            throw new WorkerException("El campo provincia no está seleccionado.");
        }
        profession = lstProfession.getSelectedValue();
        if (profession == null) {
            throw new WorkerException("No hay una profesión seleccionada.");
        }

        return new Worker(id, name, surnameOne, surnameTwo, province, profession);
    }

}
