/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Person;
import Model.PersonException;
import Model.Sex;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author AaronFM
 */
public class form2 extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form2() {
        initComponents();
        loadRadioButtons();
        loadCheckBox();
        people = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSexGroup = new javax.swing.ButtonGroup();
        btnStudiesGroup = new javax.swing.ButtonGroup();
        pnlDataLicense = new javax.swing.JPanel();
        pnlLicense4 = new javax.swing.JPanel();
        chkA = new javax.swing.JCheckBox();
        chkB = new javax.swing.JCheckBox();
        chkC = new javax.swing.JCheckBox();
        chkD = new javax.swing.JCheckBox();
        chkE = new javax.swing.JCheckBox();
        pnlData = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSurnameOne = new javax.swing.JLabel();
        txtSurnameOne = new javax.swing.JTextField();
        lblSurnameTwo = new javax.swing.JLabel();
        txtSurnameTwo = new javax.swing.JTextField();
        pnlSex = new javax.swing.JPanel();
        rdbtnSexMale = new javax.swing.JRadioButton();
        rdbtnSexFemale = new javax.swing.JRadioButton();
        pnlStudies = new javax.swing.JPanel();
        rdbtnStudiesNone = new javax.swing.JRadioButton();
        rdbtnStudiesESO = new javax.swing.JRadioButton();
        rdbtnStudiesBach = new javax.swing.JRadioButton();
        rdbtnStudiesFP = new javax.swing.JRadioButton();
        rdbtnStudiesUni = new javax.swing.JRadioButton();
        rdbtnStudiesOther = new javax.swing.JRadioButton();
        txtStudiesOther = new javax.swing.JTextField();
        pnlManage = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(468, 558));
        setResizable(false);

        pnlDataLicense.setMaximumSize(new java.awt.Dimension(436, 386));
        pnlDataLicense.setMinimumSize(new java.awt.Dimension(436, 386));

        pnlLicense4.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulación Máxima"));
        pnlLicense4.setMaximumSize(new java.awt.Dimension(160, 230));
        pnlLicense4.setPreferredSize(new java.awt.Dimension(160, 230));
        pnlLicense4.setLayout(new javax.swing.BoxLayout(pnlLicense4, javax.swing.BoxLayout.Y_AXIS));

        chkA.setText("A");
        pnlLicense4.add(chkA);

        chkB.setText("B");
        pnlLicense4.add(chkB);

        chkC.setText("C");
        pnlLicense4.add(chkC);

        chkD.setText("D");
        pnlLicense4.add(chkD);

        chkE.setText("E");
        pnlLicense4.add(chkE);

        pnlData.setMaximumSize(new java.awt.Dimension(420, 22));
        pnlData.setMinimumSize(new java.awt.Dimension(420, 22));
        pnlData.setPreferredSize(new java.awt.Dimension(420, 22));
        pnlData.setLayout(null);

        lblDNI.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDNI.setLabelFor(txtDNI);
        lblDNI.setText("DNI");
        lblDNI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlData.add(lblDNI);
        lblDNI.setBounds(0, 0, 103, 22);

        txtDNI.setText("12345678A");
        pnlData.add(txtDNI);
        txtDNI.setBounds(108, 0, 103, 22);

        lblName.setLabelFor(txtName);
        lblName.setText("Nombre");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlData.add(lblName);
        lblName.setBounds(0, 27, 103, 22);

        txtName.setText("Pepito");
        pnlData.add(txtName);
        txtName.setBounds(108, 27, 103, 22);

        lblSurnameOne.setLabelFor(txtSurnameTwo);
        lblSurnameOne.setText("Apellido 1");
        lblSurnameOne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlData.add(lblSurnameOne);
        lblSurnameOne.setBounds(0, 54, 103, 22);

        txtSurnameOne.setText("Palotes");
        pnlData.add(txtSurnameOne);
        txtSurnameOne.setBounds(108, 54, 103, 22);

        lblSurnameTwo.setLabelFor(txtSurnameOne);
        lblSurnameTwo.setText("Apellido 2");
        lblSurnameTwo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlData.add(lblSurnameTwo);
        lblSurnameTwo.setBounds(0, 81, 103, 22);

        txtSurnameTwo.setText("Perez");
        pnlData.add(txtSurnameTwo);
        txtSurnameTwo.setBounds(108, 81, 103, 22);

        pnlSex.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        pnlSex.setMaximumSize(new java.awt.Dimension(212, 210));
        pnlSex.setMinimumSize(new java.awt.Dimension(212, 210));
        pnlSex.setPreferredSize(new java.awt.Dimension(212, 210));
        pnlSex.setLayout(new javax.swing.BoxLayout(pnlSex, javax.swing.BoxLayout.PAGE_AXIS));

        btnSexGroup.add(rdbtnSexMale);
        rdbtnSexMale.setSelected(true);
        rdbtnSexMale.setText("Hombre");
        rdbtnSexMale.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnSexMale.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnSexMale.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnSexMale.setPreferredSize(new java.awt.Dimension(100, 31));
        pnlSex.add(rdbtnSexMale);

        btnSexGroup.add(rdbtnSexFemale);
        rdbtnSexFemale.setText("Mujer");
        rdbtnSexFemale.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnSexFemale.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnSexFemale.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnSexFemale.setPreferredSize(new java.awt.Dimension(100, 31));
        pnlSex.add(rdbtnSexFemale);

        pnlStudies.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulación Máxima"));
        pnlStudies.setMaximumSize(new java.awt.Dimension(212, 210));

        btnStudiesGroup.add(rdbtnStudiesNone);
        rdbtnStudiesNone.setSelected(true);
        rdbtnStudiesNone.setText("Ninguna");
        rdbtnStudiesNone.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnStudiesNone.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesNone.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesNone.setPreferredSize(new java.awt.Dimension(100, 31));

        btnStudiesGroup.add(rdbtnStudiesESO);
        rdbtnStudiesESO.setText("ESO");
        rdbtnStudiesESO.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnStudiesESO.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesESO.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesESO.setPreferredSize(new java.awt.Dimension(100, 31));

        btnStudiesGroup.add(rdbtnStudiesBach);
        rdbtnStudiesBach.setText("Bachillerato");
        rdbtnStudiesBach.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnStudiesBach.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesBach.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesBach.setPreferredSize(new java.awt.Dimension(100, 31));

        btnStudiesGroup.add(rdbtnStudiesFP);
        rdbtnStudiesFP.setText("FP");
        rdbtnStudiesFP.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnStudiesFP.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesFP.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesFP.setPreferredSize(new java.awt.Dimension(100, 31));

        btnStudiesGroup.add(rdbtnStudiesUni);
        rdbtnStudiesUni.setText("Universidad");
        rdbtnStudiesUni.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnStudiesUni.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesUni.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesUni.setPreferredSize(new java.awt.Dimension(100, 31));

        btnStudiesGroup.add(rdbtnStudiesOther);
        rdbtnStudiesOther.setText("Otros:");
        rdbtnStudiesOther.setMargin(new java.awt.Insets(5, 10, 5, 5));
        rdbtnStudiesOther.setMaximumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesOther.setMinimumSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesOther.setPreferredSize(new java.awt.Dimension(100, 31));
        rdbtnStudiesOther.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbtnStudiesOtherStateChanged(evt);
            }
        });

        txtStudiesOther.setText("jTextField1");
        txtStudiesOther.setMargin(new java.awt.Insets(2, 2, 2, 2));
        txtStudiesOther.setMaximumSize(new java.awt.Dimension(100, 25));
        txtStudiesOther.setMinimumSize(new java.awt.Dimension(100, 25));
        txtStudiesOther.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout pnlStudiesLayout = new javax.swing.GroupLayout(pnlStudies);
        pnlStudies.setLayout(pnlStudiesLayout);
        pnlStudiesLayout.setHorizontalGroup(
            pnlStudiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudiesLayout.createSequentialGroup()
                .addComponent(rdbtnStudiesOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStudiesOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlStudiesLayout.createSequentialGroup()
                .addGroup(pnlStudiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnStudiesNone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnStudiesESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnStudiesBach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnStudiesFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnStudiesUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlStudiesLayout.setVerticalGroup(
            pnlStudiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudiesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(rdbtnStudiesNone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rdbtnStudiesESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rdbtnStudiesBach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rdbtnStudiesFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rdbtnStudiesUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlStudiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnStudiesOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudiesOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlManage.add(btnSave);

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlManage.add(btnSearch);

        txtSearch.setText("Buscar...");
        txtSearch.setMinimumSize(new java.awt.Dimension(200, 25));
        txtSearch.setPreferredSize(new java.awt.Dimension(200, 25));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnlManage.add(txtSearch);

        javax.swing.GroupLayout pnlDataLicenseLayout = new javax.swing.GroupLayout(pnlDataLicense);
        pnlDataLicense.setLayout(pnlDataLicenseLayout);
        pnlDataLicenseLayout.setHorizontalGroup(
            pnlDataLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLicenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDataLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDataLicenseLayout.createSequentialGroup()
                        .addGroup(pnlDataLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlLicense4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlData, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDataLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlStudies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlDataLicenseLayout.setVerticalGroup(
            pnlDataLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLicenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDataLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDataLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlStudies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLicense4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean isValid = true;
        StringBuilder violations = new StringBuilder("Formulario incorrecto. A corregir:\n");
        isValid = validateFields(violations);
        if (isValid) {
            Person person;
            try {
                person = generateNewPerson();
            } catch (PersonException ex) {
                errorMessage(ex.getMessage());
                return;
            }
            if (checkIfPersonExists(person.getDNI())) {
                errorMessage("DNI ya registrado.");
            }
            people.add(person);
            infoMessage("Added: " + person);
        } else {
            errorMessage(violations.toString());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void rdbtnStudiesOtherStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbtnStudiesOtherStateChanged
        setOtherStudiesState();
    }//GEN-LAST:event_rdbtnStudiesOtherStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        findPerson(txtSearch.getText()).ifPresentOrElse(
                this::loadPersondata,
                () -> errorMessage("No hay tal persona registrada.")
        );

    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new form2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup btnSexGroup;
    private javax.swing.ButtonGroup btnStudiesGroup;
    private javax.swing.JCheckBox chkA;
    private javax.swing.JCheckBox chkB;
    private javax.swing.JCheckBox chkC;
    private javax.swing.JCheckBox chkD;
    private javax.swing.JCheckBox chkE;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSurnameOne;
    private javax.swing.JLabel lblSurnameTwo;
    private javax.swing.JPanel pnlData;
    private javax.swing.JPanel pnlDataLicense;
    private javax.swing.JPanel pnlLicense4;
    private javax.swing.JPanel pnlManage;
    private javax.swing.JPanel pnlSex;
    private javax.swing.JPanel pnlStudies;
    private javax.swing.JRadioButton rdbtnSexFemale;
    private javax.swing.JRadioButton rdbtnSexMale;
    private javax.swing.JRadioButton rdbtnStudiesBach;
    private javax.swing.JRadioButton rdbtnStudiesESO;
    private javax.swing.JRadioButton rdbtnStudiesFP;
    private javax.swing.JRadioButton rdbtnStudiesNone;
    private javax.swing.JRadioButton rdbtnStudiesOther;
    private javax.swing.JRadioButton rdbtnStudiesUni;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStudiesOther;
    private javax.swing.JTextField txtSurnameOne;
    private javax.swing.JTextField txtSurnameTwo;
    // End of variables declaration//GEN-END:variables
    List<JCheckBox> chkList;
    List<Person> people;

    private void infoMessage(String message) {
        JOptionPane.showMessageDialog(rootPane, message, "Registro", JOptionPane.INFORMATION_MESSAGE);
    }

    private void errorMessage(String message) {
        JOptionPane.showMessageDialog(rootPane, message, "Error en el registro", JOptionPane.ERROR_MESSAGE);
    }

    private void loadRadioButtons() {
        rdbtnStudiesNone.setActionCommand("Sin estudios.");
        rdbtnStudiesESO.setActionCommand("ESO");
        rdbtnStudiesBach.setActionCommand("Bachillerato");
        rdbtnStudiesFP.setActionCommand("FP");
        rdbtnStudiesUni.setActionCommand("Universidad");
        rdbtnStudiesOther.setActionCommand("Otros");
    }

    private void loadCheckBox() {
        chkList = Arrays.asList(chkA, chkB, chkC, chkD, chkE);
    }

    private void setOtherStudiesState() {
        if (rdbtnStudiesOther.isSelected()) {
            txtStudiesOther.setEnabled(true);
        } else {
            if (!txtStudiesOther.getText().isEmpty()) {
                txtStudiesOther.setText("");
            }
            txtStudiesOther.setEnabled(false);
        }
    }

    private Sex selectSex() {
        if (rdbtnSexMale.isSelected()) {
            return Sex.MALE;
        } else {
            return Sex.FEMALE;
        }
    }

    private List<String> getLicenses() {
        return chkList.stream().filter(AbstractButton::isSelected)
                .map((t) -> t.getActionCommand())
                .toList();

    }

    private String selectDegree() throws PersonException {
        StringBuilder degree = new StringBuilder(btnStudiesGroup.getSelection().getActionCommand());
        if (degree.toString().equalsIgnoreCase("Otros")) {
            if (txtStudiesOther.getText().isBlank()) {
                throw new Model.PersonException("No hay datos en otros estudios.");
            }
            degree.append(Person.OTHER_SEPARATOR).append(txtStudiesOther.getText());
        }
        return degree.toString();
    }

    private Person generateNewPerson() throws PersonException {
        Person person = new Person(
                txtDNI.getText(), txtName.getText(),
                txtSurnameOne.getText(), txtSurnameTwo.getText(),
                selectSex(), getLicenses(), selectDegree()
        );
        return person;
    }

    private boolean checkIfPersonExists(String dni) {
        return people.stream().anyMatch(person -> (person.getDNI().equalsIgnoreCase(dni)));
    }

    private Optional<Person> findPerson(String dni) {
        return people.stream().filter((person) -> dni.equalsIgnoreCase(person.getDNI())).findFirst();
    }

    private void loadPersondata(Person person) {
        txtDNI.setText(person.getDNI());
        txtName.setText(person.getName());
        txtSurnameTwo.setText(person.getSurnameOne());
        txtSurnameOne.setText(person.getSurnameTwo());
        loadLicensesFromPerson(person.getLicense());
        loadSexFromPerson(person);
        loadDegreeFromPerson(person);

    }

    private void loadLicensesFromPerson(List<String> licenses) {
        chkList.forEach(chk -> {
            if (licenses.contains(chk.getText())) {
                chk.setSelected(true);
            } else if (chk.isSelected()) {
                chk.setSelected(false);
            }
        });
    }

    private void loadSexFromPerson(Person person) {
        if (person.getSex() == Sex.MALE) {
            rdbtnSexMale.setSelected(true);
        } else {
            rdbtnSexFemale.setSelected(true);
        }
    }

    private void loadDegreeFromPerson(Person person) {
        String degree = person.getDegree();
        String target;
        String[] split = null;
        btnStudiesGroup.clearSelection();
        if (degree.contains(Person.OTHER_SEPARATOR)) {
            split = degree.split(Person.OTHER_SEPARATOR);
            target = split[0];
        } else {
            target = degree;
        }
        Iterator<AbstractButton> elements = btnStudiesGroup.getElements().asIterator();
        while (elements.hasNext()) {
            AbstractButton next = elements.next();
            if (next.getActionCommand().equals(target)) {
                next.setSelected(true);
            }
            if (split != null) {
                txtStudiesOther.setText(split[1]);
            }
        }

    }

    private boolean validateFields(StringBuilder violations) {
        boolean valid = true;
        if(txtDNI.getText().isBlank()){
            valid = false;
            violations.append("- El campo DNI.\n");
        }
        if(txtName.getText().isBlank()){
            valid = false;
            violations.append("- El campo Nombre.\n");
        }
        if(txtDNI.getText().isBlank()){
            valid = false;
            violations.append("- El campo Apellido 1.\n");
        }
        if(txtDNI.getText().isBlank()){
            valid = false;
            violations.append("- El campo Apellido 2.");
        }
        return valid;
    }

}
