/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author AaronFM
 */
public class padre extends javax.swing.JFrame {

    /**
     * Creates new form padre
     */
    public padre() {
        initComponents();
        lstWindows.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGrpShow = new javax.swing.ButtonGroup();
        btnGrpHide = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnTypeA = new javax.swing.JButton();
        btnTypeB = new javax.swing.JButton();
        btnTypeC = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rdBtnATypeShow = new javax.swing.JRadioButton();
        rdBtnBTypeShow = new javax.swing.JRadioButton();
        rdBtnCTypeShow = new javax.swing.JRadioButton();
        rdBtnAllTypesShow = new javax.swing.JRadioButton();
        btnShow = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rdBtnATypeHide = new javax.swing.JRadioButton();
        rdBtnBTypeHide = new javax.swing.JRadioButton();
        rdBtnCTypeHide = new javax.swing.JRadioButton();
        rdBtnAllTypeHide = new javax.swing.JRadioButton();
        btnHide = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnListShow = new javax.swing.JButton();
        btnListHide = new javax.swing.JButton();
        btnListClose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstWindows = new javax.swing.JList<>();
        lblWindowInfo = new javax.swing.JLabel();
        lblWindowCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PADRE");
        setMinimumSize(new java.awt.Dimension(696, 190));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(filler3);

        btnTypeA.setText("Hija A");
        btnTypeA.setMaximumSize(new java.awt.Dimension(100, 25));
        btnTypeA.setMinimumSize(new java.awt.Dimension(100, 25));
        btnTypeA.setPreferredSize(new java.awt.Dimension(100, 25));
        btnTypeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypeAActionPerformed(evt);
            }
        });
        jPanel1.add(btnTypeA);

        btnTypeB.setText("Hija B");
        btnTypeB.setMaximumSize(new java.awt.Dimension(100, 25));
        btnTypeB.setMinimumSize(new java.awt.Dimension(100, 25));
        btnTypeB.setPreferredSize(new java.awt.Dimension(100, 25));
        btnTypeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypeBActionPerformed(evt);
            }
        });
        jPanel1.add(btnTypeB);

        btnTypeC.setText("Hija C");
        btnTypeC.setMaximumSize(new java.awt.Dimension(100, 25));
        btnTypeC.setMinimumSize(new java.awt.Dimension(100, 25));
        btnTypeC.setPreferredSize(new java.awt.Dimension(100, 25));
        btnTypeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypeCActionPerformed(evt);
            }
        });
        jPanel1.add(btnTypeC);
        jPanel1.add(filler4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        btnGrpShow.add(rdBtnATypeShow);
        rdBtnATypeShow.setSelected(true);
        rdBtnATypeShow.setText("Tipo A");
        rdBtnATypeShow.setActionCommand(TYPE_A);
        jPanel3.add(rdBtnATypeShow);

        btnGrpShow.add(rdBtnBTypeShow);
        rdBtnBTypeShow.setText("Tipo B");
        rdBtnBTypeShow.setActionCommand(TYPE_B);
        jPanel3.add(rdBtnBTypeShow);

        btnGrpShow.add(rdBtnCTypeShow);
        rdBtnCTypeShow.setText("Tipo C");
        rdBtnCTypeShow.setActionCommand(TYPE_C);
        jPanel3.add(rdBtnCTypeShow);

        btnGrpShow.add(rdBtnAllTypesShow);
        rdBtnAllTypesShow.setText("Todas");
        rdBtnAllTypesShow.setActionCommand(ALL);
        jPanel3.add(rdBtnAllTypesShow);

        btnShow.setText("Mostrar");
        btnShow.setMaximumSize(new java.awt.Dimension(100, 25));
        btnShow.setMinimumSize(new java.awt.Dimension(100, 25));
        btnShow.setPreferredSize(new java.awt.Dimension(100, 25));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel3.add(btnShow);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ocultar"));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        btnGrpHide.add(rdBtnATypeHide);
        rdBtnATypeHide.setSelected(true);
        rdBtnATypeHide.setText("Tipo A");
        rdBtnATypeHide.setActionCommand(TYPE_A);
        jPanel4.add(rdBtnATypeHide);

        btnGrpHide.add(rdBtnBTypeHide);
        rdBtnBTypeHide.setText("Tipo B");
        rdBtnBTypeHide.setActionCommand(TYPE_B);
        jPanel4.add(rdBtnBTypeHide);

        btnGrpHide.add(rdBtnCTypeHide);
        rdBtnCTypeHide.setText("Tipo C");
        rdBtnCTypeHide.setActionCommand(TYPE_C);
        jPanel4.add(rdBtnCTypeHide);

        btnGrpHide.add(rdBtnAllTypeHide);
        rdBtnAllTypeHide.setText("Todas");
        rdBtnAllTypeHide.setActionCommand(ALL);
        jPanel4.add(rdBtnAllTypeHide);

        btnHide.setText("Ocultar");
        btnHide.setMaximumSize(new java.awt.Dimension(100, 25));
        btnHide.setMinimumSize(new java.awt.Dimension(100, 25));
        btnHide.setPreferredSize(new java.awt.Dimension(100, 25));
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });
        jPanel4.add(btnHide);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventanas Hijas"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnListShow.setText("Mostrar");
        btnListShow.setMaximumSize(new java.awt.Dimension(100, 25));
        btnListShow.setMinimumSize(new java.awt.Dimension(100, 25));
        btnListShow.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListShowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel5.add(btnListShow, gridBagConstraints);

        btnListHide.setText("Ocultar");
        btnListHide.setMaximumSize(new java.awt.Dimension(100, 25));
        btnListHide.setMinimumSize(new java.awt.Dimension(100, 25));
        btnListHide.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListHideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel5.add(btnListHide, gridBagConstraints);

        btnListClose.setText("Cerrar");
        btnListClose.setMaximumSize(new java.awt.Dimension(100, 25));
        btnListClose.setMinimumSize(new java.awt.Dimension(100, 25));
        btnListClose.setPreferredSize(new java.awt.Dimension(100, 25));
        btnListClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel5.add(btnListClose, gridBagConstraints);

        jScrollPane2.setViewportView(lstWindows);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 76;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel5.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(jPanel5, gridBagConstraints);

        lblWindowInfo.setText("Número de hijos actuales: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(lblWindowInfo, gridBagConstraints);

        lblWindowCount.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(lblWindowCount, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTypeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypeAActionPerformed
        generateChildDialog(TYPE_A);
    }//GEN-LAST:event_btnTypeAActionPerformed

    private void btnTypeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypeBActionPerformed
        generateChildDialog(TYPE_B);
    }//GEN-LAST:event_btnTypeBActionPerformed


    private void btnTypeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypeCActionPerformed
        generateChildDialog(TYPE_C);
    }//GEN-LAST:event_btnTypeCActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        String actionCommand = btnGrpShow.getSelection().getActionCommand();
        manageDialogsByType(actionCommand, true);
    }//GEN-LAST:event_btnShowActionPerformed


    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        String actionCommand = btnGrpHide.getSelection().getActionCommand();
        manageDialogsByType(actionCommand, false);
    }//GEN-LAST:event_btnHideActionPerformed

    private void btnListShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListShowActionPerformed
        lstWindows.getSelectedValuesList().forEach(child -> child.setVisible(true));
    }//GEN-LAST:event_btnListShowActionPerformed

    private void btnListHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListHideActionPerformed
        lstWindows.getSelectedValuesList().forEach(child -> child.setVisible(false));
    }//GEN-LAST:event_btnListHideActionPerformed

    private void btnListCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCloseActionPerformed
        lstWindows.getSelectedValuesList()
                .forEach(
                        (element) -> {
                            element.setVisible(false);
                            listModel.removeElement(element);
                            childDialogs.remove(element);
                        });
    }//GEN-LAST:event_btnListCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(padre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new padre().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpHide;
    private javax.swing.ButtonGroup btnGrpShow;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnListClose;
    private javax.swing.JButton btnListHide;
    private javax.swing.JButton btnListShow;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnTypeA;
    private javax.swing.JButton btnTypeB;
    private javax.swing.JButton btnTypeC;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblWindowCount;
    private javax.swing.JLabel lblWindowInfo;
    private javax.swing.JList<ChildDialog> lstWindows;
    private javax.swing.JRadioButton rdBtnATypeHide;
    private javax.swing.JRadioButton rdBtnATypeShow;
    private javax.swing.JRadioButton rdBtnAllTypeHide;
    private javax.swing.JRadioButton rdBtnAllTypesShow;
    private javax.swing.JRadioButton rdBtnBTypeHide;
    private javax.swing.JRadioButton rdBtnBTypeShow;
    private javax.swing.JRadioButton rdBtnCTypeHide;
    private javax.swing.JRadioButton rdBtnCTypeShow;
    // End of variables declaration//GEN-END:variables
    private static final String TYPE_A = "A";
    private static final String TYPE_B = "B";
    private static final String TYPE_C = "C";
    private static final String ALL = "ALL";

    List<ChildDialog> childDialogs = new ArrayList<>();
    DefaultListModel<ChildDialog> listModel = new DefaultListModel<>();

    private int getCountByType(String type) {
        return (int) childDialogs.stream().filter(
                (child) -> child.getTypeTitle().equalsIgnoreCase(type)
        ).count();
    }

    private void updateCountLabel() {
        lblWindowCount.setText(String.valueOf(childDialogs.size()));
    }

    private void generateChildDialog(String typeConstant) {
        ChildDialog child = new ChildDialog(this, typeConstant, getCountByType(typeConstant));
        child.setVisible(true);
        childDialogs.add(child);
        listModel.add(listModel.size(), child);
        updateCountLabel();
    }

    public void manageDialogsByType(String actionCommand, boolean show) {
        if (actionCommand.equals(ALL)) {
            childDialogs.forEach((child) -> child.setVisible(show));
        } else {
            childDialogs.stream()
                    .filter(child -> child.getTypeTitle().equals(actionCommand))
                    .forEach(child -> child.setVisible(show));
        }
    }
}
