/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.CardLayout;

/**
 *
 * @author AaronFM
 */
public class Ex4 extends javax.swing.JFrame {

    /**
     * Creates new form Ex4
     */
    public Ex4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAmarillo = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        btnAzul = new javax.swing.JRadioButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        btnVerde = new javax.swing.JRadioButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pnlDerecha = new javax.swing.JPanel();
        pnlAmarillo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlAzul = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        pnlVerde = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 300));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(filler3);

        buttonGroup1.add(btnAmarillo);
        btnAmarillo.setSelected(true);
        btnAmarillo.setText("AMARILLO");
        btnAmarillo.setAlignmentY(1.0F);
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });
        jPanel1.add(btnAmarillo);
        jPanel1.add(filler1);

        buttonGroup1.add(btnAzul);
        btnAzul.setText("AZUL");
        btnAzul.setAlignmentY(1.0F);
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });
        jPanel1.add(btnAzul);
        jPanel1.add(filler2);

        buttonGroup1.add(btnVerde);
        btnVerde.setText("VERDE");
        btnVerde.setAlignmentY(1.0F);
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerde);
        jPanel1.add(filler4);

        getContentPane().add(jPanel1);

        pnlDerecha.setBackground(new java.awt.Color(0, 0, 0));
        pnlDerecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDerecha.setMinimumSize(new java.awt.Dimension(10, 300));
        pnlDerecha.setPreferredSize(new java.awt.Dimension(200, 300));
        pnlDerecha.setLayout(new java.awt.CardLayout());

        pnlAmarillo.setBackground(new java.awt.Color(255, 255, 51));
        pnlAmarillo.setLayout(new javax.swing.BoxLayout(pnlAmarillo, javax.swing.BoxLayout.PAGE_AXIS));

        jButton1.setText("jButton1");
        pnlAmarillo.add(jButton1);

        jButton2.setText("jButton2");
        pnlAmarillo.add(jButton2);

        jButton3.setText("jButton3");
        pnlAmarillo.add(jButton3);

        jButton4.setText("jButton4");
        pnlAmarillo.add(jButton4);

        pnlDerecha.add(pnlAmarillo, "amarillo");

        pnlAzul.setBackground(new java.awt.Color(51, 153, 255));
        pnlAzul.setLayout(new javax.swing.BoxLayout(pnlAzul, javax.swing.BoxLayout.PAGE_AXIS));

        jRadioButton1.setText("jRadioButton1");
        pnlAzul.add(jRadioButton1);

        jRadioButton2.setText("jRadioButton2");
        pnlAzul.add(jRadioButton2);

        jRadioButton4.setText("jRadioButton4");
        pnlAzul.add(jRadioButton4);

        jRadioButton5.setText("jRadioButton5");
        pnlAzul.add(jRadioButton5);

        jRadioButton6.setText("jRadioButton6");
        pnlAzul.add(jRadioButton6);

        pnlDerecha.add(pnlAzul, "azul");

        pnlVerde.setBackground(new java.awt.Color(51, 255, 51));
        pnlVerde.setLayout(new javax.swing.BoxLayout(pnlVerde, javax.swing.BoxLayout.PAGE_AXIS));

        jCheckBox1.setText("jCheckBox1");
        pnlVerde.add(jCheckBox1);

        jCheckBox2.setText("jCheckBox2");
        pnlVerde.add(jCheckBox2);

        jCheckBox3.setText("jCheckBox3");
        pnlVerde.add(jCheckBox3);

        jCheckBox4.setText("jCheckBox4");
        pnlVerde.add(jCheckBox4);

        pnlDerecha.add(pnlVerde, "verde");

        getContentPane().add(pnlDerecha);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        ((CardLayout)pnlDerecha.getLayout()).show(pnlDerecha, "amarillo");
    }//GEN-LAST:event_btnAmarilloActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        ((CardLayout)pnlDerecha.getLayout()).show(pnlDerecha, "azul");
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        ((CardLayout)pnlDerecha.getLayout()).show(pnlDerecha, "verde");
    }//GEN-LAST:event_btnVerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAmarillo;
    private javax.swing.JRadioButton btnAzul;
    private javax.swing.JRadioButton btnVerde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JPanel pnlAmarillo;
    private javax.swing.JPanel pnlAzul;
    private javax.swing.JPanel pnlDerecha;
    private javax.swing.JPanel pnlVerde;
    // End of variables declaration//GEN-END:variables
}
