/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.CardLayout;
import java.awt.Dimension;

/**
 *
 * @author AaronFM
 */
public class Ex6 extends javax.swing.JFrame {

    /**
     * Creates new form Ex6
     */
    public Ex6() {
        initComponents();
        jButton5.setMinimumSize(new Dimension(200, (int)(jButton3.getMinimumSize().getHeight()/2)));
        jButton5.setPreferredSize(new Dimension(200, (int)(jButton3.getPreferredSize().getHeight()/2)));
        jButton5.setMaximumSize(new Dimension(200, (int)(jButton3.getMaximumSize().getHeight()/2)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton2 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jCheckBox2 = new javax.swing.JCheckBox();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jRadioButton2 = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAmarillo = new javax.swing.JRadioButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        btnAzul = new javax.swing.JRadioButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        btnVerde = new javax.swing.JRadioButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel5 = new javax.swing.JPanel();
        pnlAmarillo = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        pnlAzul = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        pnlVerde = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 5));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 30, 30));

        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel1.add(jLabel1);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        jTextField1.setText("jTextField1");
        jTextField1.setMaximumSize(new java.awt.Dimension(400, 100));
        jTextField1.setMinimumSize(new java.awt.Dimension(400, 100));
        jTextField1.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel1.add(jTextField1);

        jCheckBox1.setText("jCheckBox1");
        jPanel1.add(jCheckBox1);

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.setMaximumSize(new java.awt.Dimension(400, 100));
        jRadioButton1.setMinimumSize(new java.awt.Dimension(400, 100));
        jRadioButton1.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel1.add(jRadioButton1);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 5));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler2);

        jButton2.setText("jButton2");
        jButton2.setAlignmentY(1.0F);
        jPanel2.add(jButton2);
        jPanel2.add(filler3);

        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setAlignmentY(1.0F);
        jPanel2.add(jCheckBox2);
        jPanel2.add(filler4);

        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.setAlignmentY(1.0F);
        jPanel2.add(jRadioButton2);
        jPanel2.add(filler1);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 5));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jButton3.setText("jButton3");
        jButton3.setAlignmentX(1.0F);
        jButton3.setMaximumSize(new java.awt.Dimension(200, 100000));
        jButton3.setPreferredSize(new java.awt.Dimension(200, 100000));
        jPanel3.add(jButton3);

        jButton4.setText("jButton4");
        jButton4.setAlignmentX(1.0F);
        jButton4.setMaximumSize(new java.awt.Dimension(200, 100));
        jButton4.setMinimumSize(new java.awt.Dimension(200, 100));
        jButton4.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel3.add(jButton4);

        jButton5.setText("jButton5");
        jButton5.setAlignmentX(1.0F);
        jButton5.setMaximumSize(new java.awt.Dimension(200, 100000));
        jButton5.setPreferredSize(new java.awt.Dimension(200, 100000));
        jPanel3.add(jButton5);

        jButton6.setText("jButton6");
        jButton6.setAlignmentX(1.0F);
        jButton6.setMaximumSize(new java.awt.Dimension(200, 100));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 100));
        jButton6.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel3.add(jButton6);

        getContentPane().add(jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 5));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 278));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel4.add(filler5);

        buttonGroup1.add(btnAmarillo);
        btnAmarillo.setSelected(true);
        btnAmarillo.setText("AMARILLO");
        btnAmarillo.setAlignmentY(1.0F);
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });
        jPanel4.add(btnAmarillo);
        jPanel4.add(filler6);

        buttonGroup1.add(btnAzul);
        btnAzul.setText("AZUL");
        btnAzul.setAlignmentY(1.0F);
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });
        jPanel4.add(btnAzul);
        jPanel4.add(filler7);

        buttonGroup1.add(btnVerde);
        btnVerde.setText("VERDE");
        btnVerde.setAlignmentY(1.0F);
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });
        jPanel4.add(btnVerde);
        jPanel4.add(filler8);

        jPanel7.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setLayout(new java.awt.CardLayout());

        pnlAmarillo.setBackground(new java.awt.Color(255, 255, 51));
        pnlAmarillo.setLayout(new javax.swing.BoxLayout(pnlAmarillo, javax.swing.BoxLayout.PAGE_AXIS));

        jButton7.setText("jButton1");
        pnlAmarillo.add(jButton7);

        jButton8.setText("jButton2");
        pnlAmarillo.add(jButton8);

        jButton9.setText("jButton3");
        pnlAmarillo.add(jButton9);

        jButton10.setText("jButton4");
        pnlAmarillo.add(jButton10);

        jPanel5.add(pnlAmarillo, "amarillo");

        pnlAzul.setBackground(new java.awt.Color(51, 153, 255));
        pnlAzul.setLayout(new javax.swing.BoxLayout(pnlAzul, javax.swing.BoxLayout.PAGE_AXIS));

        jRadioButton3.setText("jRadioButton1");
        pnlAzul.add(jRadioButton3);

        jRadioButton4.setText("jRadioButton2");
        pnlAzul.add(jRadioButton4);

        jRadioButton5.setText("jRadioButton4");
        pnlAzul.add(jRadioButton5);

        jRadioButton6.setText("jRadioButton5");
        pnlAzul.add(jRadioButton6);

        jRadioButton7.setText("jRadioButton6");
        pnlAzul.add(jRadioButton7);

        jPanel5.add(pnlAzul, "azul");

        pnlVerde.setBackground(new java.awt.Color(51, 255, 51));
        pnlVerde.setLayout(new javax.swing.BoxLayout(pnlVerde, javax.swing.BoxLayout.PAGE_AXIS));

        jCheckBox3.setText("jCheckBox1");
        pnlVerde.add(jCheckBox3);

        jCheckBox4.setText("jCheckBox2");
        pnlVerde.add(jCheckBox4);

        jCheckBox5.setText("jCheckBox3");
        pnlVerde.add(jCheckBox5);

        jCheckBox6.setText("jCheckBox4");
        pnlVerde.add(jCheckBox6);

        jPanel5.add(pnlVerde, "verde");

        jPanel7.add(jPanel5);

        getContentPane().add(jPanel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        ((CardLayout)jPanel5.getLayout()).show(jPanel5, "amarillo");
    }//GEN-LAST:event_btnAmarilloActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        ((CardLayout)jPanel5.getLayout()).show(jPanel5, "azul");
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        ((CardLayout)jPanel5.getLayout()).show(jPanel5, "verde");
    }//GEN-LAST:event_btnVerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAmarillo;
    private javax.swing.JRadioButton btnAzul;
    private javax.swing.JRadioButton btnVerde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlAmarillo;
    private javax.swing.JPanel pnlAzul;
    private javax.swing.JPanel pnlVerde;
    // End of variables declaration//GEN-END:variables
}
